# Generated by Django 4.1.9 on 2023-06-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.FileField(upload_to="images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_starred", models.BooleanField(default=False)),
            ],
        ),
    ]
